//  함수에서 에러를 발생 시킬때에는 throw 를 사용하고, 
// 에러를 잡아낼 때에는 try/catch 문을 사용합니다.

// ※ 다음의 숫자들이 각각 어떤 순서로 출력되는지 예측해보자

{
    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    // TODO
}

